abstract_target 'CutBoxAll' do
    platform :osx, '10.13'

    pod 'RxSwift'

    target 'CutBox' do
        script_phase :name => 'Sign', :script => 'scripts/sign.sh'
        pod 'JSONSchema', git: 'https://github.com/kylef/JSONSchema.swift'
        pod 'KeyHolder'
        pod 'Sparkle'
        pod 'RxCocoa'
        pod 'SwiftyStringScore',  git: 'git@github.com:8bytes/SwiftyStringScore'
    end

    target 'CutBoxUnitTests' do
        script_phase :name => 'Sign', :script => 'scripts/sign.sh'
        pod 'JSONSchema', git: 'https://github.com/kylef/JSONSchema.swift'
        pod 'KeyHolder'
        pod 'Quick'
        pod 'Nimble'
        pod 'Sparkle'
        pod 'RxCocoa'
        pod 'SwiftyStringScore',  git: 'git@github.com:8bytes/SwiftyStringScore'
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
        end
      end
    end
end
